export default {
    REACT_APP_API_URL_LOGIN: process.env.REACT_APP_API_URL_LOGIN,
    REACT_APP_API_URL_USERS: process.env.REACT_APP_API_URL_USERS, 
    REACT_APP_API_URL_TIMEFRAMES: process.env.REACT_APP_API_URL_TIMEFRAMES,
    REACT_APP_API_URL_PTOS: process.env.REACT_APP_API_URL_PTOS,
    REACT_APP_API_URL_PTODAYS: process.env.REACT_APP_API_URL_PTODAYS, 
    REACT_APP_API_KEY: process.env.REACT_APP_API_KEY,
}